name: Build & Test

on:
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core SDKs
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: 'Backend: Restore'
        run: dotnet restore
      - name: 'Backend: Build'
        run: dotnet build --no-restore
      - name: 'Backend: Test'
        run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

      - name: Publish Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: test/**/*/TestResults/coverage.info
          fail_ci_if_error: false
          gcov_ignore: test/**/*
